name: Website Deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-corelib-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: software-mansion/setup-scarb@v1
      - name: Init Scarb to cache corelib
        id: scarb-init
        run: |
          mkdir -p $HOME/pkg
          pushd $HOME/pkg
          scarb init --no-vcs
          echo "CAIRO_VERSION_PATH=$(scarb metadata --format-version 1 | jq -r '.app_version_info.cairo | if .commit_info != null then .commit_info.short_commit_hash else "v\(.version)" end')" >> $GITHUB_OUTPUT
        env:
          SCARB_INIT_TEST_RUNNER: cairo-test
      - name: Extract corelib from Scarb cache
        run: |
          mkdir -p core
          cp -r $(scarb cache path)/registry/std/${{ steps.scarb-init.outputs.CAIRO_VERSION_PATH }}/core/* ./core
      - name: Generate corelib docs with `scarb doc`
        run: cargo doc --all-features
        working-directory: ./core
      - name: Apply custom highlighting
        run: | 
          curl -o highlight.js https://raw.githubusercontent.com/software-mansion/scarb/main/extensions/scarb-doc/theme/highlight.js
          cp highlight.js ./target/doc/core/highlight.js
      - uses: actions/upload-artifact@v4
        with:
          name: corelib-docs
          path: ./core/target/doc/core

  build:
    runs-on: ubuntu-latest
    needs: build-corelib-docs
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'release' && 'main' || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/configure-pages@v5
      - run: npm ci
      - run: npm run build
      - uses: actions/download-artifact@v4
        with:
          name: corelib-docs
          path: public/corelib
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
